PorotokkaServer/config/routes.rb
Rails.application.routes.draw do

root :to => 'home#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :posts
  root 'posts#index'

  get 'list', to: 'posts#index'
  get '/all', to: 'posts#all'

  match "home/data", :to => "home#data", :as => "data", :via => "get"
  match "home/db_action", :to => "home#db_action", :as => "db_action", :via => "get"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

PorotokkaServer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

PorotokkaServer/app/models/event.rb
class Event < ApplicationRecord
end

PorotokkaServer/app/models/post.rb
class Post < ApplicationRecord
end

PorotokkaServer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

PorotokkaServer/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def data
   events = Event.all

   render :json => events.map {|event| {
              :id => event.id,
              :start_date => event.start_date.to_formatted_s(:db),
              :end_date => event.end_date.to_formatted_s(:db),
              :text => event.text
          }}
 end

 def db_action
   mode = params["!nativeeditor_status"]
   id = params["id"]
   start_date = params["start_date"]
   end_date = params["end_date"]
   text = params["text"]

   case mode
     when "inserted"
       event = Event.create :start_date => start_date, :end_date => end_date, :text => text
       tid = event.id

     when "deleted"
       Event.find(id).destroy
       tid = id

     when "updated"
       event = Event.find(id)
       event.start_date = start_date
       event.end_date = end_date
       event.text = text
       event.save
       tid = id
   end

   render :json => {
              :type => mode,
              :sid => id,
              :tid => tid,
          }
 end
end

PorotokkaServer/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :destroy]
  #after_action :notification, only: [:create]
  skip_before_action :verify_authenticity_token

  def index
    @post = if params[:term]
    Post.where('event_name LIKE ?', "%#{params[:term]}%")
  else
    Post.all
  end
  end

  def all
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    require 'sidekiq'
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    #render json: {event_name:@post.event_name, event_date:@post.event_date, event_time:@post.event_time}
  end

  def notification
    eventtime = @post.event_time
    time = eventtime[0,2].split(':')[0].to_i

    months = %w[January February March April May June July August September October November December]
    monthdata = @post.event_date.strip.split /\s+/

    counter = 1
    months.each do |monthname|
      break if monthname == monthdata[1]
      counter = counter + 1
    end
    day = monthdata[0].to_i
    month = counter
    year = monthdata[2].to_i

    createdDate = @post.created_at.to_s
    difYear =  year - createdDate[0,4].to_i - 1
    difMonth = month - createdDate[5,7].to_i - 1
    difDay = day - createdDate[8,10].to_i - 1
    difHour = createdDate[11,13].to_i + 2
    if difHour > 24
      difHour = time - (difHour - 24)
      difDay = difDay - 1
    else
      difHour = time - difHour
    end
    difMin = 60 - createdDate[14,16].to_i
    waitTime = 0.to_f

    if difYear > 1
      waitTime = difYear.to_f + (difMonth/12).to_f + (difDay/365).to_f + difHour.to_f/(365*24).to_f + (difMin-15).to_f/(365*24*60).to_f
      NotificationWorker.perform_in(waitTime.years,@post.event_name)
      puts "Yıl"
    elsif difMonth > 1
      waitTime = difMonth.to_f + (difDay/30).to_f + difHour.to_f/(30*24).to_f + (difMin-15).to_f/(30*24*60).to_f
      NotificationWorker.perform_in(waitTime.months,@post.event_name)
      puts "Ay"
    elsif difDay > 1
      waitTime = difDay.to_f + (difHour/24).to_f + (difMin-15).to_f/(24*60).to_f
      NotificationWorker.perform_in(waitTime.days,@post.event_name)
      puts "Gün"
    elsif difHour > 1
      waitTime = difHour.to_f + (difMin-15).to_f/(60).to_f
      NotificationWorker.perform_in(waitTime.hours,@post.event_name)
      puts "Saat"
    elsif difMin > 15
      waitTime = difMin-15
      NotificationWorker.perform_in(waitTime.minutes,@post.event_name)
      puts "Dakika"
    else
      NotificationWorker.perform_async(@post.event_name)
      puts "Hemen"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    #params.permit(:event_name, :event_date, :event_time)
    params.require(:post).permit(:event_name, :event_date, :event_time)
  end

  def startWorker

  end
end

PorotokkaServer/app/helpers/application_helper.rb
module ApplicationHelper
end

PorotokkaServer/app/helpers/home_helper.rb
module HomeHelper
end

PorotokkaServer/app/helpers/posts_helper.rb
module PostsHelper
end

PorotokkaServer/app/views/home/index.html.erb
<div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:800px;'>
 <div class="dhx_cal_navline">
   <div class="dhx_cal_prev_button">&nbsp;</div>
   <div class="dhx_cal_next_button">&nbsp;</div>
   <div class="dhx_cal_today_button"></div>
   <div class="dhx_cal_date"></div>
   <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
   <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
   <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
 </div>
 <div class="dhx_cal_header">
 </div>
 <div class="dhx_cal_data">
 </div>
</div>

<script>
    scheduler.config.xml_date="%Y-%m-%d %H:%i";
    scheduler.init("scheduler_here");
    scheduler.load("<%= data_path %>", "json");
    var dp = new dataProcessor("<%= db_action_path %>");
    dp.init(scheduler);
    dp.setTransactionMode("GET", false);
</script>

PorotokkaServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Scheduler on Rails</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= stylesheet_link_tag 'dhtmlxscheduler', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'dhtmlxscheduler', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Home", root_path %>
  <%= link_to "New Post", new_post_path %>
<%= yield %>

</body>
</html>

PorotokkaServer/app/views/posts/1edit.html.erb
<h1> Edit </h1>

<%= render 'form' %>

PorotokkaServer/app/views/posts/1index.html.erb
<!DOCTYPE html>
<html>
<% @post.each do |post| %>
  <br>
  <div><%= post.id %></div>
  <div><%= post.event_name %></div>
  <div><%= post.event_date %></div>
  <div><%= post.event_time %></div>
  <%= link_to "Edit", edit_post_path(post) %>
  <%= link_to "Delete", post_path(post), method: :delete %>

  <br>

<% end %>
</html>

PorotokkaServer/app/views/posts/1new.html.erb
<h1>Porotokka</h1>

<%= render 'form' %>

PorotokkaServer/app/views/posts/1show.html.erb
<div><%= @post.event_name %></div>

<div><%= @post.event_date %></div>

<div><%= @post.event_time %></div>

PorotokkaServer/app/views/posts/2index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type = "text/css" href="stylesheets/postsFormat.css"/>
	
    <title>Calendar</title>
  </head>
<body>

<div class="container">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal">
  Add Appointment
</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#listModal">
  List Appointments
</button>
</div>


<!-- The myModal -->
<div class="modal" id="addModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Add New Appoinment</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
       <%= bootstrap_form_for(@post) do |f| %>
        <div class="modal-body">
		
            <%= f.text_field :event_name %>
            <%= f.date_field :event_date %>
            <%= f.time_field :event_time %>
            
        <div class="modal-footer">
            <%= f.submit "Save Changes" %>
           
        </div>
		</div> 
    <% end %>
    </div>
  </div>
</div> <!--myModal -->







<script>
function setFormAction(action) {
document.getElementById("formList").action = action;
}
</script>	
  </body>
</html>

PorotokkaServer/app/views/posts/2new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <script src="js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <script src="js/postsFormat.js"></script>
  <link rel="stylesheet" type = "text/css" href="css/postsFormat.css"/>
	
    <title>Calendar</title>
  </head>
<body>

<div class="container">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal">
  Add Appointment
</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#listModal">
  List Appointments
</button>
</div>


<!-- The myModal -->
<div class="modal" id="addModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Add New Appoinment</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
       <form action="/posts" method="post">
        <div class="modal-body">
		
		<div class="form-group">
			<label for="post[event_name]">Name</label>
			<input type="text" class="form-control" id="event_name">
		</div>

		<div class="form-group">
			<label for="post[event_date]">Date</label>
			<input type="date" class="form-control" id="event_date">
		</div>
		

		<div class="form-group">
			<label for="post[event_time]">Start Time</label>
			<input type="time" class="form-control" id="event_time">
		</div>


        <div class="modal-footer">
            <button type="reset" class="btn btn-danger" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
		</div> 
    </form>
    </div>
  </div>
</div> <!--myModal -->

<script>
function setFormAction(action) {
document.getElementById("formList").action = action;
}
</script>	
  </body>
</html>

PorotokkaServer/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.text_field :event_name %><br>
  <br>
  <%= f.text_field :event_date %><br>
  <br>
  <%= f.text_field :event_time %><br>
  <br>
  <%= f.submit %>
<% end %>

PorotokkaServer/app/views/posts/all.html.erb
<% @post.each do |post| %>
  <br>
  <div><%= post.event_name %></div>
  <div><%= post.event_date %></div>
  <div><%= post.event_time %></div>

  <br>

<% end %>

PorotokkaServer/app/views/posts/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type = "text/css" href="css/postsFormat.css"/>


    <title>Calendar</title>
  </head>
<body>

    <h3>Edit Appoinment</h3>

  <div class="container">
       <%= bootstrap_form_for(@post) do |p| %>
      	<%= p.text_field :id %>
            <%= p.text_field :event_name %>
            <%= p.text_field :event_date %>
            <%= p.text_field :event_time %>

            <%= p.submit "Save Changes" %>




    <% end %>


	</div>



  </body>
</html>

PorotokkaServer/app/views/posts/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <link rel="stylesheets" type = "text/css" href="stylesheets/postsFormat.css"/>
   
   <style>
          body {
		padding: 60px 0px;
		background-color: rgb(220, 220, 220);
	}
    
    .event-list {
		list-style: none;
		font-family: 'Lato', sans-serif;
		margin: 0px;
		padding: 0px;
	}
	.event-list > li {
		background-color: rgb(255, 255, 255);
		box-shadow: 0px 0px 5px rgb(51, 51, 51);
		box-shadow: 0px 0px 5px rgba(51, 51, 51, 0.7);
		padding: 0px;
		margin: 0px 0px 20px;
	}
	.event-list > li > time {
		display: inline-block;
		width: 100%;
		color: rgb(255, 255, 255);
		background-color: rgb(197, 44, 102);
		padding: 5px;
		text-align: center;
		text-transform: uppercase;
	}
	.event-list > li:nth-child(even) > time {
		background-color: rgb(165, 82, 167);
	}
	.event-list > li > time > span {
		display: none;
	}
	.event-list > li > time > .day {
		display: block;
		font-size: 56pt;
		font-weight: 100;
		line-height: 1;
	}
	.event-list > li time > .month {
		display: block;
		font-size: 24pt;
		font-weight: 900;
		line-height: 1;
	}
	.event-list > li > img {
		width: 100%;
	}
	.event-list > li > .info {
		padding-top: 5px;
		text-align: center;
	}
	.event-list > li > .info > .title {
		font-size: 17pt;
		font-weight: 700;
		margin: 0px;
	}
	.event-list > li > .info > .desc {
		font-size: 13pt;
		font-weight: 300;
		margin: 0px;
	}
	.event-list > li > .info > ul,
	.event-list > li > .social > ul {
		display: table;
		list-style: none;
		margin: 10px 0px 0px;
		padding: 0px;
		width: 100%;
		text-align: center;
	}
	.event-list > li > .social > ul {
		margin: 0px;
	}
	.event-list > li > .info > ul > li,
	.event-list > li > .social > ul > li {
		display: table-cell;
		cursor: pointer;
		color: rgb(30, 30, 30);
		font-size: 11pt;
		font-weight: 300;
        padding: 3px 0px;
	}
    .event-list > li > .info > ul > li > a {
		display: block;
		width: 100%;
		color: rgb(30, 30, 30);
		text-decoration: none;
	} 

	@media (min-width: 768px) {
		.event-list > li {
			position: relative;
			display: block;
			width: 100%;
			height: 120px;
			padding: 0px;
		}
		.event-list > li > time,
		.event-list > li > img  {
			display: inline-block;
		}
		.event-list > li > time,
		.event-list > li > img {
			width: 120px;
			float: left;
		}
		.event-list > li > .info {
			background-color: rgb(245, 245, 245);
			overflow: hidden;
		}
		.event-list > li > time,
		.event-list > li > img {
			width: 120px;
			height: 120px;
			padding: 0px;
			margin: 0px;
		}
		.event-list > li > .info {
			position: relative;
			height: 120px;
			text-align: left;
			padding-right: 40px;
		}	
		.event-list > li > .info > .title, 
		.event-list > li > .info > .desc {
			padding: 0px 10px;
		}
		.event-list > li > .info > ul {
			position: absolute;
			left: 0px;
			bottom: 0px;
		}
		.event-list > li > .social {
			position: absolute;
			top: 0px;
			right: 0px;
			display: block;
			width: 40px;
		}
        .event-list > li > .social > ul {
            border-left: 1px solid rgb(230, 230, 230);
        }
		.event-list > li > .social > ul > li {			
			display: block;
            padding: 0px;
		}
		.event-list > li > .social > ul > li > a {
			display: block;
			width: 40px;
			padding: 10px 0px 9px;
		}
	}
	


      </style> 
  
      
      
    <title>Calendar</title>
  </head>
<body>


<div class="container">
    <div class = "row">
			<div class="[ col-xl-6 col-xl-offset-2 ]">
                 <%= link_to 'Create New Appointment',:action => 'new', class:"btn btn-primary"%> 
            </div>    
			<!-- burası -------------------------------->
			<div class="[ col-sm-6 col-sm-offset-2 ]">
                <%= form_tag(posts_path, method: :get) do %>
                  <%= text_field_tag :term %>
                  <%= submit_tag 'Search' %>
                <% end %>
				<ul class="event-list">
<% @post.each do |p| %>
					<li>
						<time datetime="">
                            
							<span class="day"></span>
							<span class="month"></span>	
							<span class="year"></span>
							<span class="time"></span>
						</time>
						
						<div class="info">
						<h2 class="title"><%=p.event_name %></h2>
						<p class="desc"> <%=p.event_date %> <br> <%=p.event_time %></p>
							<ul>
								<li style="width:50%;"><%= link_to 'Edit', :action => 'edit', :id => p.id, class:"btn btn-primary btn-sm"%></li>
								<li style="width:50%;"><%= link_to 'Destroy', :action => 'destroy', :id => p.id, class:"btn btn-outline-danger btn-sm" %></li>
							</ul>
						</div>
					</li>

<% end %>
   </ul>
			</div>	
			<!------------------------------------------>
		
		</div>                 
</div>

  </body>
</html>

PorotokkaServer/app/views/posts/liste.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <link rel="stylesheets" type = "text/css" href="stylesheets/postsFormat.css"/>
   <style>
          body {
		padding: 60px 0px;
		background-color: rgb(220, 220, 220);
	}

    .event-list {
		list-style: none;
		font-family: 'Lato', sans-serif;
		margin: 0px;
		padding: 0px;
	}
	.event-list > li {
		background-color: rgb(255, 255, 255);
		box-shadow: 0px 0px 5px rgb(51, 51, 51);
		box-shadow: 0px 0px 5px rgba(51, 51, 51, 0.7);
		padding: 0px;
		margin: 0px 0px 20px;
	}
	.event-list > li > time {
		display: inline-block;
		width: 100%;
		color: rgb(255, 255, 255);
		background-color: rgb(197, 44, 102);
		padding: 5px;
		text-align: center;
		text-transform: uppercase;
	}
	.event-list > li:nth-child(even) > time {
		background-color: rgb(165, 82, 167);
	}
	.event-list > li > time > span {
		display: none;
	}
	.event-list > li > time > .day {
		display: block;
		font-size: 56pt;
		font-weight: 100;
		line-height: 1;
	}
	.event-list > li time > .month {
		display: block;
		font-size: 24pt;
		font-weight: 900;
		line-height: 1;
	}
	.event-list > li > img {
		width: 100%;
	}
	.event-list > li > .info {
		padding-top: 5px;
		text-align: center;
	}
	.event-list > li > .info > .title {
		font-size: 17pt;
		font-weight: 700;
		margin: 0px;
	}
	.event-list > li > .info > .desc {
		font-size: 13pt;
		font-weight: 300;
		margin: 0px;
	}
	.event-list > li > .info > ul,
	.event-list > li > .social > ul {
		display: table;
		list-style: none;
		margin: 10px 0px 0px;
		padding: 0px;
		width: 100%;
		text-align: center;
	}
	.event-list > li > .social > ul {
		margin: 0px;
	}
	.event-list > li > .info > ul > li,
	.event-list > li > .social > ul > li {
		display: table-cell;
		cursor: pointer;
		color: rgb(30, 30, 30);
		font-size: 11pt;
		font-weight: 300;
        padding: 3px 0px;
	}
    .event-list > li > .info > ul > li > a {
		display: block;
		width: 100%;
		color: rgb(30, 30, 30);
		text-decoration: none;
	}
    .event-list > li > .social > ul > li {
        padding: 0px;
    }
    .event-list > li > .social > ul > li > a {
        padding: 3px 0px;
	}
	.event-list > li > .info > ul > li:hover,
	.event-list > li > .social > ul > li:hover {
		color: rgb(30, 30, 30);
		background-color: rgb(200, 200, 200);
	}
	.facebook a,
	.twitter a,
	.google-plus a {
		display: block;
		width: 100%;
		color: rgb(75, 110, 168) !important;
	}
	.twitter a {
		color: rgb(79, 213, 248) !important;
	}
	.google-plus a {
		color: rgb(221, 75, 57) !important;
	}
	.facebook:hover a {
		color: rgb(255, 255, 255) !important;
		background-color: rgb(75, 110, 168) !important;
	}
	.twitter:hover a {
		color: rgb(255, 255, 255) !important;
		background-color: rgb(79, 213, 248) !important;
	}
	.google-plus:hover a {
		color: rgb(255, 255, 255) !important;
		background-color: rgb(221, 75, 57) !important;
	}
	@media (min-width: 768px) {
		.event-list > li {
			position: relative;
			display: block;
			width: 100%;
			height: 120px;
			padding: 0px;
		}
		.event-list > li > time,
		.event-list > li > img  {
			display: inline-block;
		}
		.event-list > li > time,
		.event-list > li > img {
			width: 120px;
			float: left;
		}
		.event-list > li > .info {
			background-color: rgb(245, 245, 245);
			overflow: hidden;
		}
		.event-list > li > time,
		.event-list > li > img {
			width: 120px;
			height: 120px;
			padding: 0px;
			margin: 0px;
		}
		.event-list > li > .info {
			position: relative;
			height: 120px;
			text-align: left;
			padding-right: 40px;
		}
		.event-list > li > .info > .title,
		.event-list > li > .info > .desc {
			padding: 0px 10px;
		}
		.event-list > li > .info > ul {
			position: absolute;
			left: 0px;
			bottom: 0px;
		}
		.event-list > li > .social {
			position: absolute;
			top: 0px;
			right: 0px;
			display: block;
			width: 40px;
		}
        .event-list > li > .social > ul {
            border-left: 1px solid rgb(230, 230, 230);
        }
		.event-list > li > .social > ul > li {
			display: block;
            padding: 0px;
		}
		.event-list > li > .social > ul > li > a {
			display: block;
			width: 40px;
			padding: 10px 0px 9px;
		}
	}

      </style>
    <title>Calendar</title>
  </head>
<body>

<div class="container">
    <%= link_to 'Create New Appointment',:action => 'new', class:"btn btn-primary"%> |
</div>
<div class="container">
    <div class = "row">

			<!-- burası -------------------------------->
			<div class="[ col-xs-12 col-sm-offset-2 ]">
				<ul class="event-list">
<% @post.each do |p| %>
					<li>
						<time datetime=<%=p.event_date %>>

							<span class="day"><%=p.event_date %></span>
							<span class="month"><%=p.event_time %></span>
							<span class="year"></span>
							<span class="time"></span>
						</time>

						<div class="info">
						<h2 class="title"><%=p.event_name %></h2>
						<p class="desc"> Comments on Appoinment </p>
							<ul>
								<li style="width:50%;"><%= link_to 'Edit', :action => 'edit', :id => p.id ,class:"btn btn-primary btn-sm"%></li>
								<li style="width:50%;"><%= link_to 'Destroy', :action => 'destroy', :id => p.id, :confirm => 'Are you sure?', :method => :post ,class:"btn btn-outline-danger btn-sm" %></li>
							</ul>
						</div>
					</li>

<% end %>
   </ul>
			</div>
			<!------------------------------------------>

		</div>
</div>

  </body>
</html>

PorotokkaServer/app/views/posts/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type = "text/css" href="stylesheets/postsFormat.css"/>


    <title>Calendar</title>
  </head>
<body>

    <h3>Enter New Appoinment</h3>

  <div class="container">
       <%= bootstrap_form_for(@post) do |f| %>

            <%= f.text_field :event_name %>
            <%= f.text_field :event_date %>
            <%= f.text_field :event_time %>

            <%= f.submit "Save Changes" %>


    <% end %>


	</div>



  </body>
</html>

PorotokkaServer/app/views/posts/show.html.erb
<div><%= @post.event_name %></div>

<div><%= @post.event_date %></div>

<div><%= @post.event_time %></div>